services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    ports:
      - "3000:3000"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    entrypoint: ["sh","-lc"]
    command: ["npx prisma migrate deploy && echo 'migrations done'"]
    restart: "no"
